#!/usr/bin/env bash
# Install nginx and and make it return a page with a string 'Hello world!'

apt-get -y install nginx
sudo ufw 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo nginx -t
service nginx start
